# Generated by Django 6.0.1 on 2026-01-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashsale', '0002_alter_product_price_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Jhonny', max_length=100),
            preserve_default=False,
        ),
    ]
