# Generated by Django 6.0.1 on 2026-01-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashsale', '0003_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
    ]
